<?php
class MyHtmlReporter extends HtmlReporter {
    function paintPass($message){
        parent::paintPass($message);
        print "<span class=\"pass\">Pass</span>: ";
        $breadcrumb = $this->getTestList();
        array_shift($breadcrumb);
        print implode("->",$breadcrumb);
        print"->$message<br/>\n";
    }
    function getCss(){
        return parent::getCss().'.pass{ color:green;}';// TODO: Change the autogenerated stub
    }
}
?>