all: testLire testCharger testShell

testLire:
	php TestEnLisantLeFichier.php /media/uapv1601663/KINGSTON/test.txt

testCharger:
	php TestEnChargeantLeFichierEtCherchant.php /media/uapv1601663/KINGSTON/test.txt

testShell:
	php TestEnUtilisantLeShellUnix.php /media/uapv1601663/KINGSTON/test.txt
